spring:
  datasource:
    url: jdbc:oracle:thin:@//dev-db-host:1521/DEVDB
    username: dev_user
    password: dev_password
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      pool-name: DevHikariPool
      minimum-idle: 5
      maximum-pool-size: 30
      connection-test-query: SELECT 1 FROM DUAL
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
